const students = [
  {
    seatNumber: "5203123",
    name: "SHREYANSH CHATURVEDI",
    prn: "2023016402450913",
    motherName: "VANDANA",
    subjects: [
      {
        code: "58651",
        paperCode: "58651",
        marksObtained: 7,
        passingMarks: 15,
        passed: false,
      },
      {
        code: "FEC101",
        paperCode: "FEC101",
        marksObtained: 21,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "58652",
        marksObtained: 9,
        passingMarks: 18,
        passed: false,
      },
      {
        code: "FEL101",
        paperCode: "FEL101",
        marksObtained: 19,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "58655",
        marksObtained: 31,
        passingMarks: 37,
        passed: false,
      },
      {
        code: "FEL102",
        paperCode: "FEL102",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "58653",
        marksObtained: 24,
        passingMarks: 32,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 24,
        passingMarks: 32,
        passed: false,
      },
      {
        code: "58654",
        paperCode: "58654",
        marksObtained: 20,
        passingMarks: 39,
        passed: false,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 19,
        passingMarks: 39,
        passed: false,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 39,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalResult: "Unsuccessful",
  },
  {
    seatNumber: "5203133",
    name: "KATHE YASH SAMADHAN",
    prn: "2022016402105284",
    motherName: "NETRA",
    subjects: [
      {
        code: "58651",
        paperCode: "58651",
        marksObtained: 32,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "FEC101",
        paperCode: "FEC101",
        marksObtained: 17,
        passingMarks: 18,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "58652",
        marksObtained: 24,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "FEL101",
        paperCode: "FEL101",
        marksObtained: 33,
        passingMarks: 33,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "58655",
        marksObtained: 24,
        passingMarks: 37,
        passed: false,
      },
      {
        code: "FEL102",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 31,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "58653",
        marksObtained: 21,
        passingMarks: 32,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 21,
        passingMarks: 32,
        passed: false,
      },
      {
        code: "58654",
        paperCode: "58654",
        marksObtained: 18,
        passingMarks: 39,
        passed: false,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 18,
        passingMarks: 39,
        passed: false,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 18,
        passingMarks: 39,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203134",
    name: "KOLPE SAURABH KIRAN",
    prn: "2023016402450944",
    motherName: "ROHINI",
    subjects: [
      {
        code: "58651",
        paperCode: "58651",
        marksObtained: 32,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEC101",
        paperCode: "FEC101",
        marksObtained: 14,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "58652",
        marksObtained: 27,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "FEL101",
        paperCode: "FEL101",
        marksObtained: 34,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "58655",
        marksObtained: 26,
        passingMarks: 20,
        passed: false,
      },
      {
        code: "FEL102",
        paperCode: "FEL102",
        marksObtained: 33,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "58653",
        marksObtained: 27,
        passingMarks: 14,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 10,
        passingMarks: 24,
        passed: false,
      },
      {
        code: "58654",
        paperCode: "58654",
        marksObtained: 27,
        passingMarks: 14,
        passed: false,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 19,
        passingMarks: 38,
        passed: false,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 39,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203135",
    name: "JAYESH VEENA",
    prn: "2023016402450646",
    motherName: "VEENA",
    subjects: [
      {
        code: "58651",
        paperCode: "58651",
        marksObtained: 64,
        passingMarks: 77,
        passed: false,
      },
      {
        code: "FEC101",
        paperCode: "FEC101",
        marksObtained: 21,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "58652",
        marksObtained: 19,
        passingMarks: 26,
        passed: false,
      },
      {
        code: "FEL101",
        paperCode: "FEL101",
        marksObtained: 23,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "58655",
        marksObtained: 24,
        passingMarks: 33,
        passed: true,
      },
      {
        code: "FEL102",
        paperCode: "FEL102",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "58653",
        marksObtained: 24,
        passingMarks: 13,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 22,
        passingMarks: 38,
        passed: false,
      },
      {
        code: "58654",
        paperCode: "58654",
        marksObtained: 32,
        passingMarks: 14,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 19,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 39,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203136",
    name: "KOTIAN DIKSHA LAXMAN",
    prn: "2022016402105276",
    motherName: "RUPA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 23,
        passingMarks: 11,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 34,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 30,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 31,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 41,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 23,
        passingMarks: 23,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203137",
    name: "AKASH KUMAR",
    prn: "2023016402451046",
    motherName: "ANITA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 9,
        passingMarks: 11,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 45,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 31,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 39,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 10,
        passingMarks: 10,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203138",
    name: "KUMBHAR SAKSHI SUNIL",
    prn: "2022016402105744",
    motherName: "ANJALI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 52,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 10,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 42,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 34,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 38,
        passingMarks: 38,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: 5.5,
    finalGrade: "Successful",
  },
  {
    seatNumber: "5203139",
    name: "KUNDER VEEKSHITH KRISHNA",
    prn: "2023016402450782",
    motherName: "VANITHA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 48,
        passingMarks: 12,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 35,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 39,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 47,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: 6.33,
    finalGrade: "Successful",
  },
  {
    seatNumber: "5203140",
    name: "MANCHIKATLA TANAI",
    prn: "2022016402108851",
    motherName: "SATYANARAYANA - ARUNA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 25,
        passingMarks: 14,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 24,
        passingMarks: 16,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 38,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 38,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 21,
        passingMarks: 21,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203141",
    name: "MHATRE PRAJOT GANESH",
    prn: "2022016402109405",
    motherName: "NEETA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 34,
        passingMarks: 8,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 25,
        passingMarks: 15,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 35,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 36,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 36,
        passingMarks: 15,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203142",
    name: "MISHRA ABHISHEKKUMAR",
    prn: "2022016400006456",
    motherName: "JAGDISHKUMAR - SANGEETA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 50,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 39,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 48,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203143",
    name: "ABHIJITH P BIJU",
    prn: "2022016401108611",
    motherName: "INDU",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 41,
        passingMarks: 9,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 15,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 38,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 31,
        passingMarks: 16,
        passed: false,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 41,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203144",
    name: "PAGARE NARESH RAJU",
    prn: "2023016402450886",
    motherName: "MANISHA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 27,
        passingMarks: 10,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 22,
        passingMarks: 22,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 21,
        passingMarks: 18,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 37,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203142",
    name: "MISHRA ABHISHEKKUMAR",
    prn: "2022016400006456",
    motherName: "JAGDISHKUMAR - SANGEETA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 50,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 39,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 48,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203143",
    name: "ABHIJITH P BIJU",
    prn: "2022016401108611",
    motherName: "INDU",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 41,
        passingMarks: 9,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 15,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 38,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 31,
        passingMarks: 16,
        passed: false,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 41,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203144",
    name: "PAGARE NARESH RAJU",
    prn: "2023016402450886",
    motherName: "MANISHA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 27,
        passingMarks: 10,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 22,
        passingMarks: 22,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 21,
        passingMarks: 18,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 37,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203145",
    name: "PAL HARSHIT",
    prn: "2022016401982946",
    motherName: "MANJU",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 24,
        passingMarks: 8,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 44,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 33,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 18,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203146",
    name: "PATEL PIYUSH PRABHUBHAI",
    prn: "2023016402450863",
    motherName: "BERIBEN",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 29,
        passingMarks: 12,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 33,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 36,
        passingMarks: 15,
        passed: false,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 38,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 37,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203147",
    name: "JAYAN MANOJ PATIL",
    prn: "2022016402105292",
    motherName: "MANDA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 40,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 16,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 23,
        passingMarks: 21,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 43,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 41,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203148",
    name: "PATIL MIHIR SUNIL",
    prn: "2023016402450735",
    motherName: "APEKSHA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 26,
        passingMarks: 11,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 20,
        passingMarks: 14,
        passed: false,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 43,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 34,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 33,
        passingMarks: 22,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203149",
    name: "PATIL URVI UMESH",
    prn: "2023016402450727",
    motherName: "ASAWARI UMESH PATIL",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 36,
        passingMarks: 14,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 23,
        passingMarks: 14,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 40,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 34,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 22,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203150",
    name: "PATIL VINAYAK VISHWAS",
    prn: "2023016402450801",
    motherName: "KAMAL",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 48,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 25,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 33,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "FEL103",
        paperCode: "FEL103",
        marksObtained: 43,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL104",
        paperCode: "FEL104",
        marksObtained: 32,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "FEL105",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203151",
    name: "VANSH TRILOKI PURWAR",
    prn: "2023016402451062",
    motherName: "HEMA PURWAR",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 10,
        passingMarks: 10,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 6,
        passingMarks: 6,
        passed: false,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 13,
        passingMarks: 10,
        passed: false,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 22,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 28,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 37,
        passingMarks: 28,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203152",
    name: "ARYAN NARPATSINGH RAJPUROHIT",
    prn: "2022016402109386",
    motherName: "PINTU",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 24,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 28,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 36,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 34,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 37,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203153",
    name: "RATHOD GAURAV SINGH HARDEV",
    prn: "2023016402451085",
    motherName: "SITA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 16,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 34,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 27,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 36,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 36,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203154",
    name: "SALUNKHE PIYUSH SACHIN",
    prn: "2023016402450685",
    motherName: "ROHINI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 21,
        passingMarks: 12,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 30,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 26,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 34,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 24,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 42,
        passingMarks: 21,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203155",
    name: "SAMALA ABHINAV SRINIWAS",
    prn: "2022016402109355",
    motherName: "ARUNLATHA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 19,
        passingMarks: 14,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 33,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 37,
        passingMarks: 22,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203156",
    name: "SANGA ANISH MAHESH",
    prn: "2023016402450975",
    motherName: "PADMA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 41,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 23,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 33,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 47,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 33,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 42,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: 5.78,
    finalGrade: "Successful",
  },
  {
    seatNumber: "5203157",
    name: "SATVI SHREYA RANJIT",
    prn: "2023016402450693",
    motherName: "RUNALI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 24,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 23,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 24,
        passingMarks: 13,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 31,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 47,
        passingMarks: 15,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203158",
    name: "SADIYA HAFIZUDDIN SHAIKH",
    prn: "2022016402105872",
    motherName: "TASLEEMA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 31,
        passingMarks: 23,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 30,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 34,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 36,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 31,
        passingMarks: 15,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203159",
    name: "SHARMA DEV PRAMOD",
    prn: "2022016402105311",
    motherName: "SONU",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 40,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 15,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 32,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 36,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 37,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 38,
        passingMarks: 18,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: 5.31,
    finalGrade: "Successful",
  },
  {
    seatNumber: "5203160",
    name: "SHELADIYA FENIL",
    prn: "2023016402451031",
    motherName: "KAILASBEN",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 37,
        passingMarks: 12,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 49,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 33,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 44,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 37,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 20,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203161",
    name: "SHINDE SAHAS LAXMAN",
    prn: "2023016402450712",
    motherName: "SAKSHATA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 48,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 34,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 43,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 55,
        passingMarks: 22,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 44,
        passingMarks: 22,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 55,
        passingMarks: 22,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: 6.67,
    finalGrade: "Successful",
  },
  {
    seatNumber: "5203162",
    name: "SINGH SHRIDEV DAYARAM",
    prn: "2023016402451023",
    motherName: "USHADEVI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 30,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 10,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 33,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 42,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 31,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 31,
        passingMarks: 16,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203163",
    name: "VAIBHAV SINGH",
    prn: "2022016402109951",
    motherName: "AARTI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 9,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 8,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 9,
        passingMarks: 9,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 32,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 30,
        passingMarks: 13,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203164",
    name: "SONAWANE BHAVESH SUBHASH",
    prn: "2023016402450983",
    motherName: "HEMABAI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 16,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 51,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 29,
        passingMarks: 12,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 38,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 21,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203166",
    name: "THAKUR HARSH SHASHIKANT",
    prn: "2022016402105856",
    motherName: "SANGITA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 47,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 32,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 32,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 33,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 30,
        passingMarks: 12,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203167",
    name: "MAYANK NARESH THAWARE",
    prn: "2022016402114275",
    motherName: "MADHURI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 21,
        passingMarks: 8,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 16,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 30,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 30,
        passingMarks: 22,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 34,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 37,
        passingMarks: 17,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203168",
    name: "THOKAL AADITYA ANAND",
    prn: "2023016402450824",
    motherName: "PRATIMA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 47,
        passingMarks: 11,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 27,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 42,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 36,
        passingMarks: 19,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203169",
    name: "TIMMAPUR SHRUTI VENGALRAO",
    prn: "2022016402105887",
    motherName: "RAJITHA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 28,
        passingMarks: 9,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 18,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 31,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 53,
        passingMarks: 37,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 30,
        passingMarks: 14,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 49,
        passingMarks: 15,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203170",
    name: "TRIPATHI KARTHIKEY",
    prn: "2023016402450662",
    motherName: "KRISHNAMURTI - SNEHLATA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 19,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 15,
        passingMarks: 9,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 21,
        passingMarks: 10,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 39,
        passingMarks: 36,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 36,
        passingMarks: 36,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203171",
    name: "TUPARE SOHAM APPAJI",
    prn: "2023016402450832",
    motherName: "MEENA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 28,
        passingMarks: 9,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 19,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 43,
        passingMarks: 37,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 41,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 38,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 19,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203172",
    name: "UNDIRWADKAR HRUDAYNATH SUNIL",
    prn: "2023016402450991",
    motherName: "PRITAM",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 23,
        passingMarks: 11,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 12,
        passingMarks: 6,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 25,
        passingMarks: 15,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 37,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 37,
        passingMarks: 37,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203173",
    name: "UPADHYAY KATHAN NIMESH",
    prn: "2022016402109966",
    motherName: "NIRANJANA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 13,
        passingMarks: 5,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 43,
        passingMarks: 37,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 38,
        passingMarks: 36,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 37,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 37,
        passingMarks: 17,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203174",
    name: "SHIVAM VARMA",
    prn: "2022016402109332",
    motherName: "SANDHYA",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 41,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 30,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 41,
        passingMarks: 39,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 41,
        passingMarks: 18,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 18,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203175",
    name: "WADHARI HARSH HANUMANTA",
    prn: "2023016402450654",
    motherName: "LAXMI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 46,
        passingMarks: 33,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 21,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 34,
        passingMarks: 27,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 45,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 49,
        passingMarks: 33,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 40,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: 5.94,
    finalGrade: "Successful",
  },
  {
    seatNumber: "5203176",
    name: "NIKHIL SURESH YADAV",
    prn: "2023016402450751",
    motherName: "POONAM",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 21,
        passingMarks: 10,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 20,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 23,
        passingMarks: 24,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 37,
        passingMarks: 12,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 37,
        passingMarks: 19,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 15,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203177",
    name: "YADAV SACHIN KAMLESH",
    prn: "2022016402105752",
    motherName: "SUNITA DEVI",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 12,
        passingMarks: 4,
        passed: false,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 17,
        passingMarks: 17,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 21,
        passingMarks: 7,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 38,
        passingMarks: 20,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 40,
        passingMarks: 30,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 40,
        passingMarks: 15,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
  {
    seatNumber: "5203178",
    name: "SHUBHAM YADAV",
    prn: "2022016402109935",
    motherName: "MUNNI YADAV",
    subjects: [
      {
        code: "58651",
        paperCode: "FEC101",
        marksObtained: 45,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58652",
        paperCode: "FEL101",
        marksObtained: 16,
        passingMarks: 16,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL102",
        marksObtained: 42,
        passingMarks: 34,
        passed: true,
      },
      {
        code: "58653",
        paperCode: "FEL103",
        marksObtained: 33,
        passingMarks: 21,
        passed: true,
      },
      {
        code: "58654",
        paperCode: "FEL104",
        marksObtained: 40,
        passingMarks: 32,
        passed: true,
      },
      {
        code: "58655",
        paperCode: "FEL105",
        marksObtained: 39,
        passingMarks: 39,
        passed: true,
      },
    ],
    totalCredit: 18.0,
    finalCGPI: null,
    finalGrade: "Unsuccessful",
  },
];

const studentTableBody = document.querySelector("#studentTable tbody");
const searchInput = document.getElementById("searchInput");
const passFailFilter = document.getElementById("passFailFilter");
const subjectFilter = document.getElementById("subjectFilter");

const renderTable = (filteredStudents) => {
  studentTableBody.innerHTML = "";

  filteredStudents.forEach((student) => {
    const row = document.createElement("tr");

    row.innerHTML = `
            <td>${student.seatNumber}</td>
            <td>${student.name}</td>
            <td>${student.prn}</td>
            <td>${student.motherName}</td>
            <td>
                ${student.subjects
                  .map(
                    (sub) =>
                      `${sub.paperCode} (${sub.marksObtained}/${sub.passingMarks})`
                  )
                  .join("<br>")}
            </td>
            <td>${student.totalCredit}</td>
            <td>${student.finalCGPI !== null ? student.finalCGPI : "N/A"}</td>
            <td>${student.finalGrade}</td>
        `;

    studentTableBody.appendChild(row);
  });
};

const filterData = () => {
  let filteredStudents = students;

  // Search filter
  const searchText = searchInput.value.toLowerCase();
  if (searchText) {
    filteredStudents = filteredStudents.filter(
      (student) =>
        student.name.toLowerCase().includes(searchText) ||
        student.prn.includes(searchText)
    );
  }

  // Pass/Fail filter
  const passFailValue = passFailFilter.value;
  if (passFailValue) {
    const isPass = passFailValue === "pass";
    filteredStudents = filteredStudents.filter((student) =>
      student.subjects.every((sub) => sub.passed === isPass)
    );
  }

  // Subject-wise filter (example for subject 1)
  const subjectValue = subjectFilter.value;
  if (subjectValue) {
    filteredStudents = filteredStudents.filter((student) =>
      student.subjects.some((sub) => sub.paperCode === subjectValue)
    );
  }

  // Render the filtered data
  renderTable(filteredStudents);
};

// Initial render
renderTable(students);

// Event listeners for filters
searchInput.addEventListener("input", filterData);
passFailFilter.addEventListener("change", filterData);
subjectFilter.addEventListener("change", filterData);
